In [1]:
import csv
import pandas as pd
import scipy.stats as stats

In [2]:
with open('census_neighborhood_demographics_2010.csv') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    census=list(reader)

In [7]:
df = pd.DataFrame(census, columns=census[0])
df.drop(0, axis=0, inplace=True)

In [2]:
df = pd.read_pickle('../pickle_jar/df.p')

In [3]:
df.head()

,NBHD_ID,NBRHD_NAME,POPULATION_2010,HISPANIC_2010,WHITE_2010,BLACK_2010,NATIVEAM_2010,ASIAN_2010,HAWPACIS_2010,OTHER_2010,...,RENTED_AGE_25_TO_34,RENTED_AGE_35_TO_44,RENTED_AGE_45_TO_54,RENTED_AGE_55_TO_59,RENTED_AGE_60_TO_64,RENTED_AGE_65_TO_74,RENTED_AGE_75_TO_84,RENTED_AGE_85_PLUS,SHAPE_Length,SHAPE_Area
1,32,Hampden,17547.0,2505.0,11750.0,1963.0,64.0,726.0,20.0,38.0,...,1363.0,791.0,700.0,304.0,253.0,285.0,200.0,229.0,0.200466185756,0.00076769350616
2,3,Baker,4879.0,1664.0,2854.0,144.0,43.0,52.0,10.0,7.0,...,486.0,235.0,231.0,113.0,64.0,82.0,23.0,7.0,0.101766999749,0.00040579106694
3,70,Washington Park,6905.0,295.0,6356.0,28.0,9.0,119.0,3.0,13.0,...,329.0,132.0,70.0,31.0,36.0,27.0,6.0,21.0,0.0904448757114,0.000410873627371
4,13,Cherry Creek,5589.0,332.0,4896.0,79.0,17.0,168.0,4.0,3.0,...,521.0,261.0,211.0,79.0,92.0,161.0,224.0,207.0,0.0639229718933,0.000227659616089
5,22,Country Club,3001.0,94.0,2740.0,20.0,8.0,77.0,1.0,5.0,...,90.0,55.0,34.0,14.0,17.0,9.0,4.0,2.0,0.052865128293,0.000176682748962

In [111]:
df.to_pickle('pickle_jar/df.p')

In [4]:
household_df = df[['NBRHD_NAME', 'NUM_HOUSEHOLDS','ONE_PERSON_HH','ONE_PERSON_HH_MALE','ONE_PERSON_HH_FEMALE',
                   'TWO_OR_MORE_PERSON_HH','FAMILY_HHLD','HUSB_WIFE_FAM','HUSB_WIFE_NO_CHILD','HUSB_WIFE_W_CHLDR',
                   'OTHER_FAMILY','MALE_HHLDR_NO_WIFE','MALE_HHLDR_W_CHLDR','MALE_HHLDR_NO_CHILDR','FEMALE_HHLDR_NO_HUSB',
                   'FEMALE_HHLDR_W_CHILDR','FEMALE_HHLDR_NO_CHILDR','NON_FAMILY_HH','NON_FAMILY_MALE_HHLDR',
                   'NON_FAMILY_FEMALE_HHLDR','HH_W_NONRELATIVES','HH_NO_NONRELATIVES','FAMILIES']]
household_df.head()

,NBRHD_NAME,NUM_HOUSEHOLDS,ONE_PERSON_HH,ONE_PERSON_HH_MALE,ONE_PERSON_HH_FEMALE,TWO_OR_MORE_PERSON_HH,FAMILY_HHLD,HUSB_WIFE_FAM,HUSB_WIFE_NO_CHILD,HUSB_WIFE_W_CHLDR,...,MALE_HHLDR_NO_CHILDR,FEMALE_HHLDR_NO_HUSB,FEMALE_HHLDR_W_CHILDR,FEMALE_HHLDR_NO_CHILDR,NON_FAMILY_HH,NON_FAMILY_MALE_HHLDR,NON_FAMILY_FEMALE_HHLDR,HH_W_NONRELATIVES,HH_NO_NONRELATIVES,FAMILIES
1,Hampden,9320.0,4397.0,1930.0,2467.0,4923.0,4105.0,2906.0,898.0,2008.0,...,209.0,838.0,446.0,392.0,818.0,442.0,376.0,1105.0,8215.0,4105.0
2,Baker,2447.0,1137.0,596.0,541.0,1310.0,833.0,551.0,221.0,330.0,...,45.0,197.0,88.0,109.0,477.0,269.0,208.0,564.0,1883.0,833.0
3,Washington Park,3307.0,1171.0,511.0,660.0,2136.0,1695.0,1465.0,600.0,865.0,...,47.0,146.0,69.0,77.0,441.0,226.0,215.0,506.0,2801.0,1695.0
4,Cherry Creek,3542.0,2002.0,717.0,1285.0,1540.0,1194.0,977.0,169.0,808.0,...,29.0,162.0,73.0,89.0,346.0,187.0,159.0,388.0,3154.0,1194.0
5,Country Club,1289.0,342.0,113.0,229.0,947.0,822.0,722.0,300.0,422.0,...,10.0,71.0,47.0,24.0,125.0,73.0,52.0,147.0,1142.0,822.0

In [5]:
household_df.to_pickle('../pickle_jar/household_df.p')

### Looking at stats of different household makeups

In [11]:
for i in household_df.columns:
    if i != 'NBRHD_NAME':
        household_df[i] = household_df[i].astype(float)
        
household_df.dtypes

C:\Users\kbutk\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

NBRHD_NAME                  object
NUM_HOUSEHOLDS             float64
ONE_PERSON_HH              float64
ONE_PERSON_HH_MALE         float64
ONE_PERSON_HH_FEMALE       float64
TWO_OR_MORE_PERSON_HH      float64
FAMILY_HHLD                float64
HUSB_WIFE_FAM              float64
HUSB_WIFE_NO_CHILD         float64
HUSB_WIFE_W_CHLDR          float64
OTHER_FAMILY               float64
MALE_HHLDR_NO_WIFE         float64
MALE_HHLDR_W_CHLDR         float64
MALE_HHLDR_NO_CHILDR       float64
FEMALE_HHLDR_NO_HUSB       float64
FEMALE_HHLDR_W_CHILDR      float64
FEMALE_HHLDR_NO_CHILDR     float64
NON_FAMILY_HH              float64
NON_FAMILY_MALE_HHLDR      float64
NON_FAMILY_FEMALE_HHLDR    float64
HH_W_NONRELATIVES          float64
HH_NO_NONRELATIVES         float64
FAMILIES                   float64
dtype: object

In [14]:
household_stats = household_df.describe().T

skew_values = list()
for num_col in household_stats.index:
    num_col_skew = stats.skew(household_df[num_col])
    skew_values.append(num_col_skew)
    
household_stats['skew'] = skew_values

household_stats

,count,mean,std,min,25%,50%,75%,max,skew
NUM_HOUSEHOLDS,78.0,3373.166667,2145.793889,60.0,1773.75,3086.0,3985.75,10856.0,1.310566
ONE_PERSON_HH,78.0,1369.589744,1229.219554,37.0,610.50,1006.0,1653.25,7796.0,2.509207
ONE_PERSON_HH_MALE,78.0,662.205128,653.108061,27.0,290.00,453.5,785.25,4530.0,3.176542
ONE_PERSON_HH_FEMALE,78.0,707.384615,604.783942,10.0,321.25,561.0,865.25,3266.0,1.990994
TWO_OR_MORE_PERSON_HH,78.0,2003.576923,1286.550745,23.0,1103.75,1894.5,2547.50,7608.0,1.777629
FAMILY_HHLD,78.0,1602.615385,1183.566251,15.0,855.00,1290.0,2095.00,7056.0,2.234598
HUSB_WIFE_FAM,78.0,1099.320513,827.955995,13.0,550.25,962.0,1437.00,4907.0,2.025012
HUSB_WIFE_NO_CHILD,78.0,485.474359,480.004944,1.0,196.50,387.5,619.75,3051.0,3.091259
HUSB_WIFE_W_CHLDR,78.0,613.846154,410.372529,12.0,302.75,574.0,828.25,2008.0,1.207602
OTHER_FAMILY,78.0,503.294872,403.857475,2.0,234.50,401.5,683.25,2296.0,2.146382
MALE_HHLDR_NO_WIFE,78.0,146.602564,114.676432,0.0,76.75,117.5,205.50,659.0,2.048705
MALE_HHLDR_W_CHLDR,78.0,66.512821,56.468298,0.0,29.25,55.5,87.75,353.0,2.634714
MALE_HHLDR_NO_CHILDR,78.0,80.089744,61.283710,0.0,36.00,61.0,107.50,364.0,1.726940
FEMALE_HHLDR_NO_HUSB,78.0,356.692308,293.310540,2.0,163.75,285.0,488.25,1637.0,2.115386
FEMALE_HHLDR_W_CHILDR,78.0,200.051282,185.862741,1.0,76.75,156.5,262.00,1102.0,2.574536
FEMALE_HHLDR_NO_CHILDR,78.0,156.641026,115.812542,1.0,78.00,128.5,207.75,659.0,1.548337
NON_FAMILY_HH,78.0,400.961538,315.352305,7.0,194.25,325.0,526.75,1859.0,1.982709
NON_FAMILY_MALE_HHLDR,78.0,226.435897,178.368697,2.0,109.75,187.5,284.50,1034.0,2.073063
NON_FAMILY_FEMALE_HHLDR,78.0,174.525641,139.106679,3.0,81.00,138.5,240.50,825.0,1.880167
HH_W_NONRELATIVES,78.0,540.474359,350.857677,8.0,291.75,463.5,701.50,1941.0,1.394060
HH_NO_NONRELATIVES,78.0,2832.692308,1833.137133,52.0,1464.50,2668.5,3370.50,8915.0,1.336733
FAMILIES,78.0,1602.615385,1183.566251,15.0,855.00,1290.0,2095.00,7056.0,2.234598

In [ ]:
household_df

In [60]:
temp_upper = household_df['HUSB_WIFE_W_CHLDR'].mean() + household_df['HUSB_WIFE_W_CHLDR'].std()
temp_lower = 0.5*household_df['HUSB_WIFE_W_CHLDR'].mean()
temp_list = []
temp_dict = {}
            
        
for j in household_df['HUSB_WIFE_W_CHLDR']:
    if j > temp_upper:
        temp_list.append('high')
    elif j < temp_lower:
        temp_list.append('lower')
    else:
        temp_list.append('average')
temp_dict['HUSB_WIFE_W_CHLDR'] = temp_list

temp_dict

{'HUSB_WIFE_W_CHLDR': ['high',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'lower',
  'average',
  'lower',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'high',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'high',
  'average',
  'average',
  'average',
  'average',
  'average',
  'high',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'high',
  'average',
  'average',
  'lower',
  'average',
  'high',
  'lower',
  'lower',
  'average',
  'high',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'high',
  'high',
  'high',
  'average']}

In [61]:
temp_upper = household_df['MALE_HHLDR_NO_WIFE'].mean() + household_df['MALE_HHLDR_NO_WIFE'].std()
temp_lower = 0.5*household_df['MALE_HHLDR_NO_WIFE'].mean()
temp_list = []



for j in household_df['MALE_HHLDR_NO_WIFE']:
    if j > temp_upper:
        temp_list.append('high')
    elif j < temp_lower:
        temp_list.append('lower')
    else:
        temp_list.append('average')
temp_dict['MALE_HHLDR_NO_WIFE'] = temp_list

temp_dict

{'HUSB_WIFE_W_CHLDR': ['high',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'lower',
  'average',
  'lower',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'high',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'high',
  'average',
  'average',
  'average',
  'average',
  'average',
  'high',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'high',
  'average',
  'average',
  'lower',
  'average',
  'high',
  'lower',
  'lower',
  'average',
  'high',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'high',
  'high',
  'high',
  'average'],
 'MALE_HHLDR_NO_WIFE': ['high',
  'average',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'lower',
  'average',
  'lower',
  'lower',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'high',
  'average',
  'average',
  'lower',
  'high',
  'high',
  'high',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'average',
  'lower',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'high',
  'average',
  'average',
  'average',
  'lower',
  'lower',
  'average',
  'average',
  'average',
  'average',
  'high',
  'average',
  'average',
  'high',
  'average',
  'average',
  'average']}

In [99]:

# temp_dict = {}
# for i in household_df.columns:
   

#         temp_list = list()
#         if household_df[i].dtype == float:
#             temp_upper = household_df[i].mean() + household_df[i].std()
#             temp_lower = 0.5*household_df[i].mean()
            
            
        
#             for j in household_df[i]:
#                 if j > temp_upper:
#                     temp_list.append('high')
#                 elif j < temp_lower:
#                     temp_list.append('lower')
#                 else:
#                     temp_list.append('average')
#             temp_dict[i] = temp_list

            
# temp_dict

In [74]:

temp_dict = {}
def get_high_low(dataframe):
    
    for i in dataframe.columns:
   

        temp_list = list()
        if dataframe[i].dtype == float:
            temp_upper = dataframe[i].mean() + dataframe[i].std()
            temp_lower = 0.5*dataframe[i].mean()
            
            
        
            for j in dataframe[i]:
                if j > temp_upper:
                    temp_list.append('high')
                elif j < temp_lower:
                    temp_list.append('lower')
                else:
                    temp_list.append('average')
            temp_dict[i] = temp_list
    return temp_dict

In [101]:
high_low = get_high_low(dataframe = household_df)
high_low_df = pd.DataFrame(high_low, index=list(range(1,79)))
high_low_df

columns_cat = ['FAMILIES_cat','FAMILY_HHLD_cat','FEMALE_HHLDR_NO_CHILDR_cat','FEMALE_HHLDR_NO_HUSB_cat','FEMALE_HHLDR_W_CHILDR_cat',
               'HH_NO_NONRELATIVES_cat','HH_W_NONRELATIVES_cat','HUSB_WIFE_FAM_cat','HUSB_WIFE_NO_CHILD_cat',
               'HUSB_WIFE_W_CHLDR_cat','MALE_HHLDR_NO_CHILDR_cat','MALE_HHLDR_NO_WIFE_cat','MALE_HHLDR_W_CHLDR_cat',
               'NON_FAMILY_FEMALE_HHLDR_cat','NON_FAMILY_HH_cat','NON_FAMILY_MALE_HHLDR_cat','NUM_HOUSEHOLDS_cat',
               'ONE_PERSON_HH_cat','ONE_PERSON_HH_FEMALE_cat','ONE_PERSON_HH_MALE_cat','OTHER_FAMILY_cat','TWO_OR_MORE_PERSON_HH_cat']

In [102]:
high_low_df

,FAMILIES,FAMILY_HHLD,FEMALE_HHLDR_NO_CHILDR,FEMALE_HHLDR_NO_HUSB,FEMALE_HHLDR_W_CHILDR,HH_NO_NONRELATIVES,HH_W_NONRELATIVES,HUSB_WIFE_FAM,HUSB_WIFE_NO_CHILD,HUSB_WIFE_W_CHLDR,...,MALE_HHLDR_W_CHLDR,NON_FAMILY_FEMALE_HHLDR,NON_FAMILY_HH,NON_FAMILY_MALE_HHLDR,NUM_HOUSEHOLDS,ONE_PERSON_HH,ONE_PERSON_HH_FEMALE,ONE_PERSON_HH_MALE,OTHER_FAMILY,TWO_OR_MORE_PERSON_HH
1,high,high,high,high,high,high,high,high,average,high,...,high,high,high,high,high,high,high,high,high,high
2,average,average,average,average,lower,average,average,average,lower,average,...,average,average,average,average,average,average,average,average,average,average
3,average,average,lower,lower,lower,average,average,average,average,average,...,average,average,average,average,average,average,average,average,lower,average
4,average,average,average,lower,lower,average,average,average,lower,average,...,lower,average,average,average,average,average,average,average,lower,average
5,average,average,lower,lower,lower,lower,lower,average,average,average,...,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower
6,average,average,average,average,average,lower,lower,lower,average,lower,...,average,lower,lower,lower,lower,lower,lower,lower,average,average
7,lower,lower,average,average,lower,lower,lower,lower,lower,lower,...,lower,lower,lower,lower,lower,lower,lower,lower,average,lower
8,lower,lower,lower,lower,lower,average,average,lower,lower,lower,...,lower,average,average,average,average,average,average,average,lower,average
9,average,average,average,average,lower,high,high,average,lower,average,...,average,high,high,high,high,high,high,high,average,average
10,lower,lower,lower,lower,lower,average,average,lower,lower,lower,...,lower,average,average,average,average,high,average,high,lower,average
11,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower,...,lower,lower,lower,lower,lower,average,lower,average,lower,lower
12,lower,lower,lower,lower,lower,average,average,lower,lower,lower,...,lower,average,average,average,average,average,average,average,lower,lower
13,lower,lower,lower,lower,lower,average,average,average,lower,average,...,lower,average,average,average,average,average,average,average,lower,average
14,average,average,average,average,average,high,high,average,average,average,...,average,high,high,high,high,high,high,high,average,average
15,average,average,lower,average,average,average,average,high,high,average,...,average,average,average,average,average,average,average,average,average,average
16,average,average,average,average,average,average,high,average,average,average,...,average,high,high,high,average,average,average,average,average,average
17,lower,lower,average,average,average,lower,lower,lower,lower,lower,...,average,lower,lower,lower,lower,lower,lower,lower,average,lower
18,average,average,average,average,lower,average,average,average,average,average,...,average,high,average,average,average,average,average,average,average,average
19,average,average,lower,lower,lower,average,lower,average,average,average,...,lower,average,lower,lower,average,lower,average,lower,lower,average
20,average,average,average,lower,lower,average,average,average,average,average,...,lower,average,average,average,average,average,average,average,lower,average
21,average,average,average,average,average,high,high,average,average,average,...,average,high,high,high,high,high,high,high,average,average
22,average,average,average,average,average,high,high,average,average,average,...,average,high,high,high,high,high,high,high,average,average
23,average,average,average,average,average,lower,average,lower,average,lower,...,average,lower,lower,average,lower,lower,lower,lower,average,average
24,average,average,high,high,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
25,average,average,average,average,average,average,average,average,average,average,...,average,lower,lower,average,average,average,average,average,average,average
26,average,average,average,lower,lower,average,high,average,average,average,...,average,high,high,high,average,average,average,average,average,average
27,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
28,high,high,average,average,average,high,high,high,average,high,...,average,average,average,average,high,average,average,average,average,high
29,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower,...,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower
30,average,average,average,average,lower,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,average,average,high,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
50,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
51,average,average,lower,average,average,average,average,lower,average,lower,...,average,average,average,average,average,average,average,average,average,average
52,average,average,average,average,average,average,average,average,average,average,...,average,lower,lower,average,average,lower,lower,lower,average,average
53,high,high,average,average,average,high,average,high,average,high,...,average,average,average,average,high,high,high,high,average,high
54,average,average,high,high,high,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
55,average,average,average,average,average,lower,average,average,average,average,...,average,lower,lower,lower,average,lower,lower,lower,average,average
56,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower,...,lower,lower,average,average,lower,lower,lower,lower,lower,lower
57,average,average,average,average,average,average,high,average,lower,average,...,average,high,high,high,average,high,high,high,average,average
58,average,average,average,average,average,average,average,average,average,high,...,average,average,average,average,average,average,average,lower,average,average
59,average,average,average,average,average,average,average,lower,lower,lower,...,average,average,average,average,average,average,average,average,average,average
60,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower,...,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower
61,average,average,lower,lower,lower,average,lower,average,average,average,...,lower,lower,lower,lower,average,average,average,lower,lower,average
62,average,average,high,average,average,high,average,average,average,high,...,average,average,average,average,high,high,high,high,high,average
63,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
64,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average
65,lower,lower,average,lower,lower,lower,lower,average,lower,average,...,lower,average,lower,lower,lower,lower,lower,lower,lower,lower
66,lower,lower,lower,average,average,lower,lower,lower,lower,lower,...,lower,lower,lower,lower,lower,lower,lower,lower,average,lower
67,average,average,lower,lower,lower,lower,lower,average,average,average,...,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower
68,lower,lower,lower,lower,lower,lower,average,lower,lower,lower,...,average,lower,average,average,lower,lower,lower,lower,lower,lower
69,average,average,average,average,average,lower,lower,lower,average,lower,...,average,lower,lower,lower,lower,lower,lower,lower,average,lower
70,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,lower,lower,lower,average,average
71,average,average,average,average,lower,lower,lower,average,lower,average,...,average,lower,lower,lower,lower,lower,lower,lower,average,lower
72,average,average,high,average,average,average,average,average,average,average,...,high,average,average,average,average,average,average,average,high,average
73,average,average,average,average,average,average,average,average,average,lower,...,average,lower,lower,lower,average,lower,lower,lower,average,average
74,average,average,average,average,average,average,average,average,average,lower,...,lower,average,average,average,average,lower,lower,lower,average,average
75,high,high,high,high,high,high,high,high,high,high,...,high,average,average,average,high,average,average,average,high,high
76,high,high,average,average,average,average,average,high,average,high,...,high,average,average,average,average,average,average,average,average,high
77,average,average,average,average,average,average,average,average,average,high,...,average,lower,lower,lower,average,average,average,average,average,average
78,average,average,average,average,average,average,average,average,average,average,...,average,average,average,average,average,average,average,average,average,average

In [103]:
high_low_df.to_pickle('../pickle_jar/household_high_low.p')